env:
  global:
    - secure: aZaxFFC+vufTbRAs27PrCvR/h2/0r6RDw4rzdmEI3iyHpbwFijasK5NeOnd1LOjMQA8qyWZc6stc3NN5CzDexACN/5Lr0b8yfGZCAOf/koJbYhSMuJh+PGJXVmkOo916hRDmfBLyGzEQxvlzfMgW7aG+wReDcXLufgdE/bnhm4I=

language: rust

script:
  - cargo build
  - cargo test
  - cargo doc

after_success:
  - curl -s 'http://www.rust-ci.org/artifacts/put?t='$RUSTCI_TOKEN | tee >/dev/stderr | sh
