[package]
name = "irc"
version = "0.1.0"
authors = [ "Stacey Ell <stacey.ell@gmail.com>" ]


[lib]
name = "irc"

[[bin]]
name = "ircbot"
path = "ircbot.rs"


[dependencies.toml]
git = "https://github.com/alexcrichton/toml-rs"

[dependencies.http]
git = "https://github.com/chris-morgan/rust-http"

